### ISSUE TITLE
TypeError in update_outlets_v1

### ISSUE THREAD

**Issue by wuestenfeld** [tyralla/hydpy#15]
While running hp.doit() an error occurs. something seems to be wrong with the pointer?

Traceback (most recent call last):
  File "P:\HydPy\Projektarbeit\globski.py", line 6, in <module>
    hp.doit()
  File "P:\HydPy\hydpy\core\hydpytools.py", line 275, in doit
    func(idx)
  File "P:\HydPy\hydpy\core\modeltools.py", line 101, in doit
    self.update_outlets()
  File "P:\HydPy\hydpy\models\globwat\globwat_model.py", line 568, in update_outlets_v1
    out.q[0] += sta.qout
TypeError: 'hydpy.cythons.pointer.PPDouble' object does not support item assignment

**Comment by tyralla** [comment]
I suspect, your unintentionally defined your outlet sequence to be 1-dimensional.  As the GlobWat model does always calculate only one output value per time step, its outlet sequence should be 0-dimensional.

If you really want it to be 1-dimensional (which might be confusing in later applications), try the following. Instead of 

```python
out.q[0] += sta.qout
```
write

```python
out.q[0][0] += sta.qout
```

in method _update_outlets_v1_.
