### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by wuestenfeld** [tyralla/hydpy#17]
This error message is not clear. It is not understandable at which point or element the error occurs. It would be helpful, if the error message is more detailed in this case.

Traceback (most recent call last):
  File "P:\HydPy\examples\globski.py", line 20, in <module>
    hp.doit()
  File "P:\HydPy\hydpy\core\hydpytools.py", line 287, in doit
    func(idx)
  File "P:\HydPy\hydpy\core\modeltools.py", line 98, in doit
    self.loaddata()
  File "P:\HydPy\hydpy\core\modeltools.py", line 112, in loaddata
    self.sequences.loaddata(self.idx_sim)
  File "P:\HydPy\hydpy\core\sequencetools.py", line 78, in loaddata
    subseqs.loaddata(idx)
  File "P:\HydPy\hydpy\core\sequencetools.py", line 326, in loaddata
    self.fastaccess.loaddata(idx)
  File "P:\HydPy\hydpy\core\sequencetools.py", line 1467, in loaddata
    getattr(self, name)[:] = values
ValueError: could not broadcast input array from shape (698) into shape (697)

**Comment by tyralla** [comment]
The GlobWat model is one first model implemented in HydPy, which uses 1-dimensional input sequences. So I did not put much effort in writing messages for the associated errors so far.  This seems to be a good occasion. I hope I will be able to do so tomorrow.

(I think, the best place to check for the correctness of the shape of the input data would be the `load_ext` method of the `IOSequence` class.)

**Comment by wuestenfeld** [comment]
This error is fixed. unfortunely it was my fault, because my data was inconsistent at certain points.

**Comment by tyralla** [comment]
Ok, good to know.  However, its good we have implemented the new error message.  This type of error can easily occur when starting to prepare a large HydPy application.
